# Generated by Django 2.1.2 on 2018-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfirst_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=2)),
                ('phno', models.IntegerField(max_length=10)),
                ('psw', models.CharField(max_length=10)),
            ],
        ),
    ]
