# Generated by Django 2.1.2 on 2018-10-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfirst_app', '0002_regform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regform',
            name='phno',
            field=models.CharField(max_length=10),
        ),
    ]
